### ISSUE TITLE
All urls are wrong

### ISSUE THREAD

**Issue by Fischmuetze** [yep/app-downloader#1]
macOS Catalina, 10.15.7 (german)
MacBook Pro 16"

I tried it out for the most popular app packages like gimp, inkscape, libreoffice, firefox but every time the url isn't work. Delivered urls:
https://download.gimp.org/pub/gimp/v./osx/gimp--x86_64.dmg
https://media.inkscape.org/dl/resources/file/Inkscape-.dmg
https://download.documentfoundation.org/libreoffice/stable//mac/x86_64/LibreOffice__MacOS_x86-64.dmg
https://download-installer.cdn.mozilla.net/pub/firefox/releases//mac/en-US/Firefox%20.dmg

Also would be great to have a better wildcard search "ink" should find "inky" but also "inkscape".

Last but not least it should be have a language selector. On a german macOS I would like download the german version of Firefox (if it would work) and not the US.

**Comment by yep** [comment]
Thanks for bringing this to my attention.
Could you please try version 1.0.4 from https://github.com/yep/app-downloader/releases and close this issue if it is fixed?

Other changes in 1.0.4:
 - Created landing page at https://yep.github.io/app-downloader
 - Added Sparkle framework for automatic updates
 - Added Let's Move framework to automatically move the app to the application folder after download
 - For each app, a description is shown. For example, for GIMP, it says: "GNU Image Manipulation Program" and "Free and open-source image editor"
 - If you search for a lot of apps, you'll hit GitHub's API request limit. The error message is more descriptive in this case now.
 
You could investigate if wildcard search is actually supported by the GitHub API. Language selector should be possible but is more work.

Maybe other contributors want to add these feature and create a pull request.
