### ISSUE TITLE
GitHub API changes

### ISSUE THREAD

**Issue by yep** [yep/app-downloader#2]
Looks like GitHub's API no longer returns results in the way it did, when this app was developed.

If anybody knows a solution or workaround I would be happy to implement it.

Until then, this app is essentially unusable, unfortunately.

**Comment by ShlomoCode** [comment]
@yep So why not make the repository "read only" and leave a message in the README?

**Comment by yep** [comment]
Release [v1.0.5](https://github.com/yep/app-downloader/releases/tag/v1.0.5) restores download functionality.

It's now using the cask.json as described at https://formulae.brew.sh/docs/api
